### ISSUE TITLE
paper-material style breaks nested Paper Elements

### ISSUE THREAD

**Issue by twlamb** [Allsteel/asi-paper#1]
The style in the asi-paper-master:

```CSS
:host ::content paper-material {
    background-color: #fff;
}
```

Breaks nested Paper elements (E.G. paper-button).  If I try to style the background color of it, it is overwrtiten since it contains a paper-material, which is being styled white by the asi-paper-master.

@mbr4nt  & @tucaz  see any issue with removing this? I've tried locally and it seems ok.
